'use client'

import { useMemo, useState } from 'react'
import { ArrowDown, ArrowUp, ArrowUpRight, CalendarDays, Clock3, Menu, MessageCircle, X, ZoomIn } from 'lucide-react'

const logoUrl = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-LL0uRRLqzeWszsJnLGkcpl6ya7QLVV.png'
const whatsappBase = 'https://api.whatsapp.com/send?phone=573218891248&text='
const quickBooking = `${whatsappBase}${encodeURIComponent('¡Hola! 😊 Me gustaría agendar una cita, ¿cuándo tienes disponibilidad? Muchas gracias!')}`

const services = [
  ['Manicure tradicional', '$20.000'], ['Semipermanente (manos)', '$50.000'], ['Semipermanente (pies)', '$45.000'],
  ['Base Rubber', '$60.000'], ['Dipping', '$70.000'], ['Soft Gel', '$90.000'], ['Acrílico con tip', '$110.000'],
]
const galleries = [
  { name: 'Semipermanente', note: 'Color, brillo y precisión', images: ['/images/Semipermanente/1.jpeg', '/images/Semipermanente/2.jpeg', '/images/Semipermanente/3.jpeg'] },
  { name: 'Rubber', note: 'Estructura natural y elegante', images: ['/images/Rubber/1.jpeg', '/images/Rubber/2.jpeg', '/images/Rubber/3.jpeg'] },
  { name: 'Soft Gel', note: 'Extensión ligera, efecto editorial', images: ['/images/SoftGel/1.jpeg', '/images/SoftGel/2.jpeg', '/images/SoftGel/3.jpeg'] },
  { name: 'Acrílico', note: 'Diseños con carácter', images: ['/images/Acrilico/1.jpeg', '/images/Acrilico/2.jpeg', '/images/Acrilico/3.jpeg'] },
]

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [bookingOpen, setBookingOpen] = useState(false)
  const [selectedImage, setSelectedImage] = useState<{ src: string; alt: string } | null>(null)
  const [name, setName] = useState('')
  const [service, setService] = useState(services[0][0])
  const [date, setDate] = useState('')
  const [time, setTime] = useState('')
  const bookingUrl = useMemo(() => {
    const message = `¡Hola Veronica! 😊 Soy ${name || '[mi nombre]'}. Me gustaría agendar ${service}${date ? ` el ${date}` : ''}${time ? ` a las ${time}` : ''}. ¿Tienen disponibilidad? Muchas gracias!`
    return `${whatsappBase}${encodeURIComponent(message)}`
  }, [name, service, date, time])
  const readyToSend = name.trim() !== '' && date !== '' && time !== ''

  return <main className="min-h-screen overflow-hidden bg-background text-foreground">
    <header className="fixed inset-x-0 top-0 z-40 border-b border-foreground/10 bg-background/80 backdrop-blur-md"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 md:h-20 md:px-10"><a href="#inicio" className="flex items-center gap-3" aria-label="Lumea inicio"><img src={logoUrl} alt="Logotipo Lumea" className="h-14 w-14 object-contain md:h-20 md:w-20" /><span className="font-serif text-sm tracking-[0.24em] text-primary md:text-base">LUMEA</span></a><nav className="hidden items-center gap-9 md:flex" aria-label="Navegación principal"><a href="#servicios" className="nav-link">Precios</a><a href="#galeria" className="nav-link">Servicios</a><a href="#estudio" className="nav-link">Visítanos</a></nav><a href={quickBooking} target="_blank" rel="noreferrer" className="hidden rounded-full bg-primary px-5 py-2.5 text-xs font-semibold tracking-[0.16em] text-primary-foreground transition-transform hover:-translate-y-0.5 md:block">AGENDAR CITA</a><button className="text-primary md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Cerrar menú' : 'Abrir menú'}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div>{menuOpen && <nav className="border-t border-foreground/10 bg-background px-5 py-6 md:hidden" aria-label="Menú móvil"><div className="flex flex-col gap-5 font-serif text-xl"><a href="#servicios" onClick={() => setMenuOpen(false)}>Precios</a><a href="#galeria" onClick={() => setMenuOpen(false)}>Servicios</a><a href="#estudio" onClick={() => setMenuOpen(false)}>Visítanos</a><a href={quickBooking} target="_blank" rel="noreferrer" className="mt-2 w-fit rounded-full bg-primary px-5 py-3 font-sans text-xs font-semibold tracking-[0.16em] text-primary-foreground">AGENDAR CITA</a></div></nav>}</header>

    <section id="inicio" className="relative flex min-h-[720px] items-end px-5 pb-14 pt-32 md:min-h-[850px] md:px-10 md:pb-20"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(7,26,64,.97)_0%,rgba(28,35,92,.75)_43%,rgba(73,35,66,.2)_100%),url('/images/main.png')] bg-cover bg-[center_35%]" /><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_32%,rgba(231,161,143,.28),transparent_30%)]" /><div className="relative z-10 mx-auto w-full max-w-7xl"><p className="mb-5 flex items-center gap-3 text-xs font-semibold tracking-[0.3em] text-primary"><span className="h-px w-10 bg-primary" /> NAIL ART & BEAUTY</p><h1 className="max-w-3xl font-serif text-6xl leading-[.92] text-foreground md:text-9xl">Tu estilo,<br /><em className="text-primary">tu firma.</em></h1><p className="mt-7 max-w-md text-sm leading-6 text-foreground/75 md:text-base">Manicure de autor para mujeres que convierten cada detalle en una declaración.</p><div className="mt-9 flex flex-wrap items-center gap-4"><a href={quickBooking} target="_blank" rel="noreferrer" className="group flex items-center gap-3 rounded-full bg-primary px-6 py-3.5 text-xs font-bold tracking-[0.16em] text-primary-foreground">RESERVAR MI CITA <ArrowUpRight size={16} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></a><a href="#galeria" className="flex items-center gap-2 px-2 text-xs font-semibold tracking-[0.16em] text-foreground/80">VER GALERÍA <ArrowDown size={14} /></a></div></div><div className="absolute bottom-8 right-6 hidden rotate-90 text-[10px] tracking-[0.32em] text-foreground/60 md:block">POPAYÁN · CAUCA</div></section>

    <section id="servicios" className="mx-auto max-w-7xl px-5 py-20 md:px-10 md:py-28"><div className="mb-12 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">01 / PRECIOS</p><h2 className="mt-3 max-w-xl font-serif text-4xl leading-tight md:text-6xl">Un ritual diseñado para <em className="text-primary">brillar.</em></h2></div><p className="max-w-xs text-sm leading-6 text-muted-foreground">Técnicas precisas, acabados impecables y una pausa que se siente solo tuya.</p></div><div className="grid border-t border-foreground/15 md:grid-cols-2">{services.map(([name, price], index) => <div key={name} className={`flex items-center justify-between border-b border-foreground/15 py-5 md:px-5 ${index % 2 === 0 ? 'md:border-r md:pr-8' : 'md:pl-8'}`}><div className="flex items-center gap-4"><span className="font-mono text-xs text-primary">0{index + 1}</span><h3 className="font-serif text-xl md:text-2xl">{name}</h3></div><span className="text-lg font-bold tracking-[0.1em] text-primary">{price}</span></div>)}</div></section>

    <section id="galeria" className="bg-secondary px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><div className="mb-12"><p className="eyebrow">02 / SERVICIOS</p><h2 className="mt-3 max-w-2xl font-serif text-4xl md:text-6xl">Técnicas reales.<br /><em className="text-primary">Resultados Lumea.</em></h2></div><div className="grid gap-12">{galleries.map((gallery) => <div key={gallery.name} className="grid gap-5 border-t border-foreground/25 pt-12 md:grid-cols-[.8fr_1.2fr] md:items-end first:border-t-0 first:pt-0"><div><p className="font-mono text-xs tracking-[0.18em] text-primary">{gallery.name.toUpperCase()}</p><h3 className="mt-2 font-serif text-4xl">{gallery.name}</h3><p className="mt-2 text-sm text-muted-foreground">{gallery.note}</p></div><div className="grid grid-cols-2 gap-3"><button type="button" onClick={() => setSelectedImage({ src: gallery.images[0], alt: `Trabajo de ${gallery.name}` })} className="group relative text-left"><img src={gallery.images[0]} alt={`Trabajo de ${gallery.name}`} className="aspect-[4/5] w-full object-cover transition-transform group-hover:scale-[1.02]" /><span className="absolute bottom-3 right-3 flex h-9 w-9 items-center justify-center bg-background/80 text-primary" aria-label={`Ampliar trabajo de ${gallery.name}`}><ZoomIn size={16} /></span></button><button type="button" onClick={() => setSelectedImage({ src: gallery.images[1], alt: `Detalle de uñas ${gallery.name}` })} className="group relative mt-8 text-left"><img src={gallery.images[1]} alt={`Detalle de uñas ${gallery.name}`} className="aspect-[4/5] w-full object-cover transition-transform group-hover:scale-[1.02]" /><span className="absolute bottom-3 right-3 flex h-9 w-9 items-center justify-center bg-background/80 text-primary" aria-label={`Ampliar detalle de ${gallery.name}`}><ZoomIn size={16} /></span></button><button type="button" onClick={() => setSelectedImage({ src: gallery.images[2], alt: `Otro trabajo de ${gallery.name}` })} className="group relative col-span-2 text-left md:col-span-1 md:mt-16"><img src={gallery.images[2]} alt={`Otro trabajo de ${gallery.name}`} className="aspect-[16/9] w-full object-cover transition-transform group-hover:scale-[1.02] md:aspect-[4/5]" /><span className="absolute bottom-3 right-3 flex h-9 w-9 items-center justify-center bg-background/80 text-primary" aria-label={`Ampliar otro trabajo de ${gallery.name}`}><ZoomIn size={16} /></span></button></div></div>)}</div></div></section>

    <section id="estudio" className="bg-primary px-5 py-20 text-primary-foreground md:px-10 md:py-28"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[.75fr_1.25fr] md:items-center"><div><p className="font-mono text-xs font-semibold tracking-[0.18em]">03 / VISÍTANOS</p><h2 className="mt-3 font-serif text-5xl leading-tight md:text-7xl">El lujo está<br />en los <em>detalles.</em></h2><p className="mt-7 max-w-md text-sm leading-7 opacity-80">Un espacio íntimo para desconectarte, elegir tu técnica y salir con manos que hablan por ti. También llevamos el ritual hasta tu puerta: ofrecemos servicio a domicilio en Popayán.</p><button onClick={() => setBookingOpen(true)} className="mt-8 flex items-center gap-2 border-b border-primary-foreground/70 pb-2 text-xs font-bold tracking-[0.18em]">ENCUENTRA TU MOMENTO <ArrowUpRight size={16} /></button></div><div><div className="aspect-[4/3] overflow-hidden border border-primary-foreground/30 bg-secondary"><iframe title="Mapa de ubicación de Lumea en Popayán, Cauca" src="https://www.google.com/maps?q=2.448528,-76.623944&z=16&output=embed" className="h-full w-full border-0 grayscale-[.15]" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div><div className="mt-4 border border-primary-foreground/30 px-5 py-4"><p className="font-mono text-[10px] tracking-[0.2em]">VISÍTANOS</p><p className="mt-1 font-serif text-lg">Popayán, Cauca</p><p className="mt-2 text-xs opacity-70">2°26&apos;54.7&quot;N 76°37&apos;26.2&quot;W · Servicio a domicilio disponible</p></div></div></div></section>

    <footer className="border-t border-foreground/10 px-5 py-8 md:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-5 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-3"><img src={logoUrl} alt="Lumea" className="h-8 w-8 object-contain" /><span className="font-serif tracking-[0.2em]">LUMEA</span></div><p className="text-xs text-muted-foreground">© 2026 Lumea.</p><a href="#inicio" className="flex items-center gap-2 text-xs font-bold tracking-[0.15em] text-primary">VOLVER ARRIBA <ArrowUp size={14} /></a></div></footer>

    {selectedImage && <div onClick={() => setSelectedImage(null)} className="modal-backdrop fixed inset-0 z-[60] flex items-center justify-center bg-background/90 p-4 backdrop-blur-md" role="dialog" aria-modal="true" aria-label="Vista ampliada de trabajo"><button type="button" onClick={() => setSelectedImage(null)} className="absolute right-4 top-4 z-10 flex h-11 w-11 items-center justify-center rounded-full bg-primary text-primary-foreground" aria-label="Cerrar imagen ampliada"><X size={22} /></button><div onClick={(event) => event.stopPropagation()} className="modal-image-content relative flex max-h-[90vh] max-w-3xl items-center justify-center"><img src={selectedImage.src} alt={selectedImage.alt} className="max-h-[86vh] max-w-full object-contain" /><p className="absolute bottom-3 left-3 bg-background/80 px-3 py-2 text-xs text-foreground">Toca X para cerrar</p></div></div>}

    {bookingOpen && <div className="modal-backdrop fixed inset-0 z-50 flex items-end justify-center bg-background/70 p-0 backdrop-blur-sm md:items-center md:p-5" role="dialog" aria-modal="true" aria-labelledby="booking-title"><div onClick={(event) => event.stopPropagation()} className="modal-sheet w-full max-w-lg border border-primary/30 bg-card p-6 shadow-2xl shadow-background/40 md:p-10"><div className="flex items-start justify-between"><div><p className="eyebrow">LUMEA / WHATSAPP</p><h2 id="booking-title" className="mt-2 font-serif text-4xl">Reserva tu ritual.</h2></div><button onClick={() => setBookingOpen(false)} aria-label="Cerrar reserva"><X size={22} /></button></div><p className="mt-4 text-sm leading-6 text-muted-foreground">Completa los datos y te llevaremos a WhatsApp con el mensaje listo para enviar.</p><p className="mt-3 border-l-2 border-primary/60 pl-3 text-xs leading-5 text-muted-foreground">La fecha y hora propuestas pueden cambiar según la disponibilidad de la manicurista. Te confirmaremos el horario por WhatsApp.</p><div className="mt-7 grid gap-4"><label className="field-label">TU NOMBRE<input value={name} onChange={(e) => setName(e.target.value)} className="booking-input" placeholder="Nombre completo" /></label><label className="field-label">TÉCNICA O SERVICIO<select value={service} onChange={(e) => setService(e.target.value)} className="booking-input">{services.map(([item]) => <option key={item}>{item}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="field-label">FECHA<input value={date} onChange={(e) => setDate(e.target.value)} type="date" className="booking-input" /></label><label className="field-label">HORA<input value={time} onChange={(e) => setTime(e.target.value)} type="time" className="booking-input" /></label></div></div><a href={readyToSend ? bookingUrl : '#'} target="_blank" rel="noreferrer" onClick={(e) => { if (!readyToSend) { e.preventDefault(); return } setBookingOpen(false) }} aria-disabled={!readyToSend} className={`mt-7 flex w-full items-center justify-center gap-2 py-4 text-xs font-bold tracking-[0.18em] text-primary-foreground transition-opacity ${readyToSend ? 'bg-primary' : 'bg-primary/40'}`}>ENVIAR A WHATSAPP <MessageCircle size={16} /></a><p className="mt-4 flex items-center justify-center gap-2 text-center text-xs text-muted-foreground"><Clock3 size={13} /> Respuesta rápida por WhatsApp</p></div></div>}
  </main>
}
